### ISSUE TITLE
plugin name/folder clash!

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_tab_icons__del#1]
https://github.com/cudatext-addons/cuda_tab_icons

**Comment by Alexey-T** [comment]
is it possible to merge your code to that plugin?

**Comment by halfbrained** [comment]
Sure, seems simple enough

**Comment by halfbrained** [comment]
@Alexey-T 
pull request - https://github.com/CudaText-addons/cuda_tab_icons/pull/2
